# Generated by Django 3.1.7 on 2021-06-17 21:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('Cart_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(default='', max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=10)),
                ('phone_num', models.IntegerField()),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_title', models.CharField(max_length=50)),
                ('product_disc', models.CharField(default='', max_length=200)),
                ('product_details', models.CharField(default='', max_length=200)),
                ('date', models.DateField(default=datetime.datetime(2021, 6, 17, 21, 22, 17, 473878, tzinfo=utc))),
                ('product_price', models.IntegerField()),
                ('product_commission', models.IntegerField(default=0)),
                ('product_size', models.CharField(max_length=2)),
                ('product_gender', models.CharField(default='F', max_length=1)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(default='', upload_to='shop/images')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.seller')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('payment_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('payment_date', models.DateField(max_length=10)),
                ('payment_type', models.CharField(max_length=10)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cart')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
            ],
        ),
        migrations.CreateModel(
            name='cart_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(max_length=2)),
                ('date_added', models.DateField()),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cart')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.products')),
            ],
        ),
    ]
